[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# https://packaging.python.org/en/latest/tutorials/packaging-projects/

[project]
name = "flux_player_adamjgrant"
version = "2.0.2"
authors = [ { name="Adam J. Grant", email="hello@adamgrant.me" } ]
description = "The Missing OS for LLMs"
readme = "README.md"
requires-python = ">=3.11.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://www.adamgrant.info/flux-player"
Issues = "https://github.com/adamjgrant/fluxplayer"

[tool.hatch.build.targets.wheel]
packages = ["flux"]

[tool.hatch.build.target.sdist.force-include]
"src/cli.py" = "flux.py"

[project.scripts]
flux = "flux.module:main"