[tool.poetry]
name = "flux player"
version = "2.0.5"
description = "The missing OS for LLMs"
authors = ["Adam Grant <hello@adamgrant.me>"]
license = "MIT"
readme = "README.md"
packages = [{include = "fluxplayer"}]

[tool.poetry.dependencies]
python = "^3.11"
ruamel-yaml = "^0.18.5"
ruamel-yaml-clib = "^0.2.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
